# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coupang.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QWidget
from selenium import webdriver
import time
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import random

class Thread(QtCore.QThread):
    def run(self):
        options = webdriver.ChromeOptions()
        options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
        self.driver = webdriver.Chrome(options=options)
        self.driver.get('https://partners.coupang.com/')
        self.driver.set_window_size(1300, 1000)
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_xpath('//*[@id="app-header"]/div[2]/div/button[1]').click()
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_xpath('//*[@id="login-email-input"]').send_keys(self.naruto.coupang_id)
        time.sleep(1)
        self.driver.find_element_by_xpath('//*[@id="login-password-input"]').send_keys(self.naruto.coupang_pw)
        time.sleep(2)
        self.driver.find_element_by_xpath('//*[@id="login-keep-state"]').click()
        self.driver.find_element_by_xpath('/html/body/div[1]/div/div/form/div[5]/button').click()
        time.sleep(5)

        user_option1 = list()
        user_option2 = list()
        user_option3 = list()
        if self.naruto.radioButton.isChecked():
            if self.naruto.checkBox_3.isChecked():
                user_option1.append("패션의류")

            if self.naruto.checkBox_4.isChecked():
                user_option1.append("패션잡화")

            if self.naruto.checkBox_5.isChecked():
                user_option1.append("화장품/미용")

            if self.naruto.checkBox_6.isChecked():
                user_option1.append("디지털/가전")

            if self.naruto.checkBox_9.isChecked():
                user_option1.append("출산/육아")

            if self.naruto.checkBox_8.isChecked():
                user_option1.append("식품")

            if self.naruto.checkBox_7.isChecked():
                user_option1.append("스포츠/레저")

            if self.naruto.checkBox_10.isChecked():
                user_option1.append("역사/생활편의")

            if self.naruto.checkBox_11.isChecked():
                user_option1.append("면세점")

            if self.naruto.checkBox_12.isChecked():
                user_option1.append("도서")

            if self.naruto.checkBox_13.isChecked():
                user_option1.append("랜덤")


            target = self.get_product_target(user_option1, 5)
            for blog in self.naruto.blog_memory:
                if blog[0].isChecked():
                    update_counter = 0
                    if self.naruto.product_counter1 == self.naruto.product_counter2 :
                        update_counter = self.naruto.product_counter1
                    else:
                        update_counter = random.randrange(self.naruto.product_counter1, (self.naruto.product_counter2+1))

                    print(target)
                    print(update_counter)
                    answer = random.sample(target, update_counter)
                    print(answer)
                    self.driver.get('https://partners.coupang.com/#affiliate/ws/link')
                    self.driver.implicitly_wait(10)
                    for search_text in answer:
                        self.driver.find_element_by_xpath('//*[@id="root"]/div/div/div[2]/div/div/div[1]/div/div/div[2]/div/div/div/div/div/div/section[3]/div/span/input').send_keys(search_text)
                        time.sleep(1)
                        self.driver.find_element_by_xpath('//*[@id="root"]/div/div/div[2]/div/div/div[1]/div/div/div[2]/div/div/div/div/div/div/section[3]/div/span/span[2]/button').click()
                        y_select = random.randrange(1, 8)



    def get_product_target(self, user_option, get_counter):
        self.driver.get('https://datalab.naver.com/')
        self.driver.implicitly_wait(10)
        product_search_name = list()
        for cate in user_option:
            self.driver.find_element_by_xpath('//*[@id="content"]/div[1]/div[3]/div[1]/a').click()
            time.sleep(1)
            for y in range(1,13):
                cate_name = self.driver.find_element_by_xpath('//*[@id="content"]/div[1]/div[3]/div[1]/ul/li['+str(y)+']').text
                if cate_name == cate :
                    self.driver.find_element_by_xpath('//*[@id="content"]/div[1]/div[3]/div[1]/ul/li['+str(y)+']').click()
                    time.sleep(1)
                    break

            for y in range(1,11):
                search_name2 = self.driver.find_element_by_xpath('//*[@id="content"]/div[1]/div[4]/div/div[1]/div/div/div[12]/div/div/ul/li['+str(y)+']/a/span').text
                product_search_name.append(search_name2)

        return product_search_name


    def stop(self):
        self.driver.quit()

class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 665)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 591, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        #아이디 입력 창
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)


        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)


        #비밀번호 입력 창
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)

        
        #로그인 버튼
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        #사용자 등록 버튼
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)



        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(840, 10, 161, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")


        #세팅 저장 버튼
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)

        #세팅 로드 버튼
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)


        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 70, 1021, 611))
        self.widget.setStyleSheet("\n"
"background-color: rgb(50, 48, 40);\n"
"")
        self.widget.setObjectName("widget")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 20, 941, 531))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 60, 891, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_6.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_3.addWidget(self.lineEdit_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_5.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_3.addWidget(self.lineEdit_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_4.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_3.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 96, 99);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(20, 170, 891, 251))
        self.tableWidget.setStyleSheet("background-color: rgb(130, 130, 130);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(34)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 120, 161, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_7.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 99, 102);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 430, 601, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_5.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_9.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_7.setStatusTip("")
        self.lineEdit_7.setWhatsThis("")
        self.lineEdit_7.setAccessibleName("")
        self.lineEdit_7.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setMaxLength(32766)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_5.addWidget(self.lineEdit_7)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_8.setStatusTip("")
        self.lineEdit_8.setWhatsThis("")
        self.lineEdit_8.setAccessibleName("")
        self.lineEdit_8.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_8.setInputMask("")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setMaxLength(32766)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_5.addWidget(self.lineEdit_8)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(640, 430, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 96, 99);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(780, 430, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")


        #쿠팡 파트너스 아이디 입력창
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(20, 20, 172, 20))
        self.lineEdit_9.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_9.setObjectName("lineEdit_9")

        #쿠팡 파트너스 비밀번호 입력창
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(200, 20, 172, 20))
        self.lineEdit_10.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lineEdit_10.setObjectName("lineEdit_10")


        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 191, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(240, 30, 81, 31))
        self.lineEdit_11.setStyleSheet("border-color: rgb(255, 255, 127);\n"
"color: rgb(255, 255, 0);")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(350, 30, 81, 31))
        self.lineEdit_12.setStyleSheet("border-color: rgb(255, 255, 127);\n"
"color: rgb(255, 255, 0);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(330, 40, 16, 16))
        self.label_6.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(450, 30, 401, 31))
        self.label_7.setStyleSheet("color: rgb(255, 255, 0);\n"
"color: rgb(255, 129, 131);")
        self.label_7.setObjectName("label_7")
        self.radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(30, 80, 231, 31))
        self.radioButton.setStyleSheet("color: rgb(85, 170, 255);")
        self.radioButton.setObjectName("radioButton")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 130, 101, 16))
        self.checkBox_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_4.setGeometry(QtCore.QRect(150, 130, 101, 16))
        self.checkBox_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_5.setGeometry(QtCore.QRect(270, 130, 101, 16))
        self.checkBox_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_6.setGeometry(QtCore.QRect(390, 130, 101, 16))
        self.checkBox_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_7.setGeometry(QtCore.QRect(630, 130, 101, 16))
        self.checkBox_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_8.setGeometry(QtCore.QRect(750, 130, 101, 16))
        self.checkBox_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_9.setGeometry(QtCore.QRect(510, 130, 101, 16))
        self.checkBox_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_10.setGeometry(QtCore.QRect(30, 160, 111, 16))
        self.checkBox_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_11.setGeometry(QtCore.QRect(150, 160, 101, 16))
        self.checkBox_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_12.setGeometry(QtCore.QRect(270, 160, 101, 16))
        self.checkBox_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_13.setGeometry(QtCore.QRect(390, 160, 101, 16))
        self.checkBox_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 0);")
        self.checkBox_13.setObjectName("checkBox_13")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 190, 231, 31))
        self.radioButton_2.setStyleSheet("color: rgb(85, 170, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_14.setGeometry(QtCore.QRect(30, 240, 101, 16))
        self.checkBox_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_15.setGeometry(QtCore.QRect(150, 240, 101, 16))
        self.checkBox_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_16.setGeometry(QtCore.QRect(270, 240, 121, 16))
        self.checkBox_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_17.setGeometry(QtCore.QRect(410, 240, 141, 16))
        self.checkBox_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_18.setGeometry(QtCore.QRect(570, 240, 101, 16))
        self.checkBox_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 0);")
        self.checkBox_18.setObjectName("checkBox_18")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 270, 161, 31))
        self.radioButton_3.setStyleSheet("color: rgb(85, 170, 255);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(200, 270, 141, 31))
        self.pushButton_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(500, 330, 331, 161))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("aa1.PNG"))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(40, 330, 301, 161))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("aa2.PNG"))
        self.label_8.setObjectName("label_8")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_19.setGeometry(QtCore.QRect(30, 380, 71, 41))
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_20.setGeometry(QtCore.QRect(470, 380, 71, 41))
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 121, 21))
        self.label_10.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 121, 21))
        self.label_11.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(20, 230, 121, 21))
        self.label_13.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(20, 330, 141, 21))
        self.label_14.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(20, 390, 121, 21))
        self.label_15.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_15.setObjectName("label_15")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(160, 20, 191, 23))
        self.pushButton_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setGeometry(QtCore.QRect(780, 20, 121, 23))
        self.pushButton_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_15.setGeometry(QtCore.QRect(160, 70, 191, 23))
        self.pushButton_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_16.setGeometry(QtCore.QRect(520, 70, 151, 23))
        self.pushButton_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_17.setGeometry(QtCore.QRect(160, 230, 151, 23))
        self.pushButton_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_21.setGeometry(QtCore.QRect(380, 20, 131, 21))
        self.checkBox_21.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_22.setGeometry(QtCore.QRect(530, 20, 131, 21))
        self.checkBox_22.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_23.setGeometry(QtCore.QRect(670, 20, 101, 21))
        self.checkBox_23.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_23.setObjectName("checkBox_23")
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(0, 50, 931, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_24.setGeometry(QtCore.QRect(380, 70, 131, 21))
        self.checkBox_24.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_25.setGeometry(QtCore.QRect(20, 110, 201, 21))
        self.checkBox_25.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_25.setObjectName("checkBox_25")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(230, 110, 191, 21))
        self.lineEdit_13.setStyleSheet("border-color: rgb(255, 255, 127);\n"
"color: rgb(255, 255, 0);")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.checkBox_26 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_26.setGeometry(QtCore.QRect(460, 110, 211, 21))
        self.checkBox_26.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_26.setObjectName("checkBox_26")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(680, 110, 191, 21))
        self.lineEdit_14.setStyleSheet("border-color: rgb(255, 255, 127);\n"
"color: rgb(255, 255, 0);")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.widget_2 = QtWidgets.QWidget(self.tab_3)
        self.widget_2.setGeometry(QtCore.QRect(0, 150, 931, 61))
        self.widget_2.setStyleSheet("background-color: rgb(158, 158, 158);\n"
"background-color: rgb(59, 59, 59);")
        self.widget_2.setObjectName("widget_2")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 191, 21))
        self.label_12.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_12.setObjectName("label_12")
        self.checkBox_27 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_27.setGeometry(QtCore.QRect(230, 20, 261, 21))
        self.checkBox_27.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_28.setGeometry(QtCore.QRect(360, 230, 131, 21))
        self.checkBox_28.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_28.setObjectName("checkBox_28")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_18.setGeometry(QtCore.QRect(500, 230, 151, 23))
        self.pushButton_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.checkBox_29 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_29.setGeometry(QtCore.QRect(20, 270, 201, 21))
        self.checkBox_29.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_30.setGeometry(QtCore.QRect(460, 270, 211, 21))
        self.checkBox_30.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_30.setObjectName("checkBox_30")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(230, 270, 191, 21))
        self.lineEdit_15.setStyleSheet("border-color: rgb(255, 255, 127);\n"
"color: rgb(255, 255, 0);")
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(680, 270, 191, 21))
        self.lineEdit_16.setStyleSheet("border-color: rgb(255, 255, 127);\n"
"color: rgb(255, 255, 0);")
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(10, 300, 931, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.checkBox_31 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_31.setGeometry(QtCore.QRect(230, 330, 121, 21))
        self.checkBox_31.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_32.setGeometry(QtCore.QRect(350, 330, 201, 21))
        self.checkBox_32.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_32.setObjectName("checkBox_32")
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setGeometry(QtCore.QRect(10, 360, 931, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.checkBox_33 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_33.setGeometry(QtCore.QRect(160, 390, 111, 21))
        self.checkBox_33.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_34.setGeometry(QtCore.QRect(290, 390, 141, 21))
        self.checkBox_34.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_34.setObjectName("checkBox_34")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_19.setGeometry(QtCore.QRect(450, 390, 151, 23))
        self.pushButton_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(620, 390, 271, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action2()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def test(self):
        print('test')

    def lineEdit_9_action(self, text):
        self.coupang_id = text

    def lineEdit_10_action(self, text):
        self.coupang_pw = text

    def lineEdit_6_action(self, text):
        self.blog_url = text
    
    def lineEdit_5_action(self, text):
        self.blog_id = text

    def lineEdit_4_action(self, text):
        self.blog_pw = text
    
    def lineEdit_3_action(self, text):
        self.blog_cate = text

    def lineEdit_7_action(self, text):
        self.posting_delay = int(text)

    def lineEdit_8_action(self, text):
        self.posting_counter = int(text)

    def lineEdit_11_action(self, text):
        self.product_counter1 = int(text)

    def lineEdit_12_action(self, text):
        self.product_counter2 = int(text)
    

    def blog_add(self):
        self.tableWidget.setRowCount(self.table_counter+1)
        c3 = QtWidgets.QCheckBox(self.blog_url)
        self.tableWidget.setCellWidget(self.table_counter, 0, c3)
        self.tableWidget.setItem(self.table_counter, 1, QtWidgets.QTableWidgetItem(self.blog_id))
        self.tableWidget.setItem(self.table_counter, 2, QtWidgets.QTableWidgetItem(self.blog_pw))
        self.tableWidget.setItem(self.table_counter, 3, QtWidgets.QTableWidgetItem(self.blog_cate))
        self.tableWidget.setItem(self.table_counter, 4, QtWidgets.QTableWidgetItem("0"))
        self.table_counter += 1
        self.blog_memory.append([c3, self.blog_id, self.blog_pw, self.blog_cate, "0"])

    def pushButton_10_action(self):
        self.worker = Thread()
        self.worker.naruto = self
        self.worker.start()

    def pushButton_11_action(self):
        self.worker.stop()

    def action2(self):
        self.table_counter = 0
        self.coupang_id = ""
        self.coupang_pw = ""
        self.blog_url = ""
        self.blog_id = ""
        self.blog_pw = ""
        self.blog_cate = ""
        self.posting_delay = 1
        self.posting_counter = 1
        self.product_counter1 = 1
        self.product_counter2 = 1
        self.blog_memory = list()
        self.pushButton_3.released.connect(self.test)
        self.lineEdit_9.textChanged[str].connect(self.lineEdit_9_action)
        self.lineEdit_10.textChanged[str].connect(self.lineEdit_10_action)
        self.lineEdit_6.textChanged[str].connect(self.lineEdit_6_action)
        self.lineEdit_5.textChanged[str].connect(self.lineEdit_5_action)
        self.lineEdit_4.textChanged[str].connect(self.lineEdit_4_action)
        self.lineEdit_3.textChanged[str].connect(self.lineEdit_3_action)
        self.pushButton_5.released.connect(self.blog_add)
        self.lineEdit_7.textChanged[str].connect(self.lineEdit_7_action)
        self.lineEdit_8.textChanged[str].connect(self.lineEdit_8_action)
        self.lineEdit_11.textChanged[str].connect(self.lineEdit_11_action)
        self.lineEdit_12.textChanged[str].connect(self.lineEdit_12_action)
        self.pushButton_10.released.connect(self.pushButton_10_action)
        self.pushButton_11.released.connect(self.pushButton_11_action)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "PW"))
        self.pushButton.setText(_translate("MainWindow", "로그인"))
        self.pushButton_2.setText(_translate("MainWindow", "사용자등록"))
        self.pushButton_3.setText(_translate("MainWindow", "세팅 저장"))
        self.pushButton_4.setText(_translate("MainWindow", "세팅 로드"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "블로그주소 입력"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "블로그 ID 입력"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "블로그 PW 입력"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "카테고리 입력(생략)"))
        self.pushButton_5.setText(_translate("MainWindow", "블로그 추가"))
        self.pushButton_6.setText(_translate("MainWindow", "블로그 불러오기"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "블로그리스트"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "아이디"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "패스워드"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "카테고리"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "작업현황"))
        self.pushButton_7.setText(_translate("MainWindow", "전체선택"))
        self.pushButton_8.setText(_translate("MainWindow", "전체해제"))
        self.checkBox_2.setText(_translate("MainWindow", "프록시 사용"))
        self.checkBox.setText(_translate("MainWindow", "테더링 사용"))
        self.pushButton_9.setText(_translate("MainWindow", "IP 불러오기"))
        self.label_3.setText(_translate("MainWindow", "포스팅 딜레이"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "분"))
        self.label_4.setText(_translate("MainWindow", "포스팅 수량"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "00"))
        self.pushButton_10.setText(_translate("MainWindow", "자동 홍보 시작"))
        self.pushButton_11.setText(_translate("MainWindow", "자동 홍보 정지"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "쿠팡 파트너스 ID(이메일) 입력"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "PW 입력"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "실행 설정"))
        self.label_5.setText(_translate("MainWindow", "★ 한 포스팅에 등록할 상품 갯수"))
        self.label_6.setText(_translate("MainWindow", "~"))
        self.label_7.setText(_translate("MainWindow", "※ 1~1 입력시 1개 / 2~2 입력시 2개 / 1~3 입력시 3개 이하 랜덤 적용"))
        self.radioButton.setText(_translate("MainWindow", "쇼핑 인기 검색어 사용 (복수 체크 가능)"))
        self.checkBox_3.setText(_translate("MainWindow", "패션의류"))
        self.checkBox_4.setText(_translate("MainWindow", "패션잡화"))
        self.checkBox_5.setText(_translate("MainWindow", "화장품/미용"))
        self.checkBox_6.setText(_translate("MainWindow", "디지털/가전"))
        self.checkBox_7.setText(_translate("MainWindow", "식품"))
        self.checkBox_8.setText(_translate("MainWindow", "스포츠/레저"))
        self.checkBox_9.setText(_translate("MainWindow", "출산/육아"))
        self.checkBox_10.setText(_translate("MainWindow", "역사/생활편의"))
        self.checkBox_11.setText(_translate("MainWindow", "면세점"))
        self.checkBox_12.setText(_translate("MainWindow", "도서"))
        self.checkBox_13.setText(_translate("MainWindow", "랜덤"))
        self.radioButton_2.setText(_translate("MainWindow", "추천 상품 (복수 체크 가능)"))
        self.checkBox_14.setText(_translate("MainWindow", "골드박스"))
        self.checkBox_15.setText(_translate("MainWindow", "로켓프레시"))
        self.checkBox_16.setText(_translate("MainWindow", "할인률 높은 상품"))
        self.checkBox_17.setText(_translate("MainWindow", "최근 많이 팔린 상품"))
        self.checkBox_18.setText(_translate("MainWindow", "랜덤"))
        self.radioButton_3.setText(_translate("MainWindow", "원하는 상품 키워드 삽입"))
        self.pushButton_12.setText(_translate("MainWindow", "파일 불러오기"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "상품 설정"))
        self.label_10.setText(_translate("MainWindow", "★ 제목에 설정"))
        self.label_11.setText(_translate("MainWindow", "★ 내용 상단 설정"))
        self.label_13.setText(_translate("MainWindow", "★ 내용 하단 설정"))
        self.label_14.setText(_translate("MainWindow", "★ 내용 하단 추가 설정"))
        self.label_15.setText(_translate("MainWindow", "★ 마무리 설정"))
        self.pushButton_13.setText(_translate("MainWindow", "제목 파일 불러오기"))
        self.pushButton_14.setText(_translate("MainWindow", "치환 파일 불러오기"))
        self.pushButton_15.setText(_translate("MainWindow", "내용 파일 불러오기"))
        self.pushButton_16.setText(_translate("MainWindow", "치환 파일 불러오기"))
        self.pushButton_17.setText(_translate("MainWindow", "내용 파일 불러오기"))
        self.checkBox_21.setText(_translate("MainWindow", "사용한 키워드 넣기"))
        self.checkBox_22.setText(_translate("MainWindow", "사용한 상품명 넣기"))
        self.checkBox_23.setText(_translate("MainWindow", "치환 단어 사용"))
        self.checkBox_24.setText(_translate("MainWindow", "치환(변경)단어 적용"))
        self.checkBox_25.setText(_translate("MainWindow", "특정단어에 사용한 키워드로 변경"))
        self.checkBox_26.setText(_translate("MainWindow", "특정단어에 사용한 상품명으로 변경"))
        self.label_12.setText(_translate("MainWindow", "★ 내용 중앙 쿠팡 광고 삽입 부분"))
        self.checkBox_27.setText(_translate("MainWindow", "쿠팡파트너스 링크우회/단축도메인 사용"))
        self.checkBox_28.setText(_translate("MainWindow", "치환(변경)단어 적용"))
        self.pushButton_18.setText(_translate("MainWindow", "치환 파일 불러오기"))
        self.checkBox_29.setText(_translate("MainWindow", "특정단어에 사용한 키워드로 변경"))
        self.checkBox_30.setText(_translate("MainWindow", "특정단어에 사용한 상품명으로 변경"))
        self.checkBox_31.setText(_translate("MainWindow", "자동원고 덧붙임 ("))
        self.checkBox_32.setText(_translate("MainWindow", "자동원고 안보이게 히든 적용)"))
        self.checkBox_33.setText(_translate("MainWindow", "태그 자동 입력"))
        self.checkBox_34.setText(_translate("MainWindow", "태그 파일 사용 입력"))
        self.pushButton_19.setText(_translate("MainWindow", "태그 파일 불러오기"))
        self.comboBox.setItemText(0, _translate("MainWindow", "전체공개"))
        self.comboBox.setItemText(1, _translate("MainWindow", "이웃공개"))
        self.comboBox.setItemText(2, _translate("MainWindow", "서로이웃공개"))
        self.comboBox.setItemText(3, _translate("MainWindow", "비공개"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "자동 초대"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
